import React from "react";
console.log("Affirmations module loaded");

const affirmation=[
        { "id": 1, "text": "I am successful." },
        { "id": 2, "text": "I am confident." },
        { "id": 3, "text": "I am powerful." },
        { "id": 4, "text": "I am strong." },
        { "id": 5, "text": "I am getting better and better every day." },
        { "id": 6, "text": "All I need is within me right now." },
        { "id": 7, "text": "I wake up motivated." },
        { "id": 8, "text": "I am an unstoppable force of nature." },
        { "id": 9, "text": "I am a living, breathing example of motivation." },
        { "id": 10, "text": "I am living with abundance." },
        { "id": 11, "text": "I am having a positive and inspiring impact on the people I come into contact with." },
        { "id": 12, "text": "I am inspiring people through my work." },
        { "id": 13, "text": "I’m rising above the thoughts that are trying to make me angry or afraid." },
        { "id": 14, "text": "Today is a phenomenal day." },
        { "id": 15, "text": "I am turning DOWN the volume of negativity in my life, while simultaneously turning UP the volume of positivity." },
        { "id": 16, "text": "I am filled with focus." },
        { "id": 17, "text": "I am not pushed by my problems; I am led by my dreams." },
        { "id": 18, "text": "I am grateful for everything I have in my life." },
        { "id": 19, "text": "I am independent and self-sufficient." },
        { "id": 20, "text": "I can be whatever I want to be." },
        { "id": 21, "text": "I am not defined by my past; I am driven by my future." },
        { "id": 22, "text": "I use obstacles to motivate me to learn and grow." },
        { "id": 23, "text": "Today will be a productive day." },
        { "id": 24, "text": "I am intelligent and focused." },
        { "id": 25, "text": "I feel more grateful each day." },
        { "id": 26, "text": "I am getting healthier every day." },
        { "id": 27, "text": "Each and every day, I am getting closer to achieving my goals." },
        { "id": 28, "text": "Through the power of my thoughts and words, incredible transformations are happening in me and within my life right now." },
        { "id": 29, "text": "I am constantly growing and evolving into a better person." },
        { "id": 30, "text": "I’m freeing myself from all destructive doubt and fear." },
        { "id": 31, "text": "I accept myself for who I am and create peace, power and confidence of mind and of heart." },
        { "id": 32, "text": "I am going to forgive myself and free myself. I deserve to forgive and be forgiven." },
        { "id": 33, "text": "I am healing and strengthening every day." },
        { "id": 34, "text": "I’ve made it through hard times before, and I’ve come out stronger and better because of them. I’m going to make it through this." },
        { "id": 35, "text": "I do not waste away a single day of my life. I squeeze every ounce of value out of each of my days on this planet—today, tomorrow, and everyday." },
        { "id": 36, "text": "I must remember the incredible power I possess within me to achieve anything I desire." },
        { "id": 37, "text": "I do not engage with people who try to penetrate my mind with unhelpful thoughts and ideas—I walk away when a person or a situation isn’t healthy for me." },
        { "id": 38, "text": "I belong in this world; there are people that care about me and my worth." },
        { "id": 39, "text": "My past might be ugly, but I am still beautiful." },
        { "id": 40, "text": "I have made mistakes, but I will not let them define me." },
        { "id": 41, "text": "My soul radiates from the inside and warms the souls of others." },
        { "id": 42, "text": "I don’t compare myself to others. The only person I compare myself to is the person I was yesterday. And as long as the person I am today is even the tiniest bit better than the person I was yesterday—I’m meeting my own definition of success." },
        { "id": 43, "text": "Note to self: I am going to make you so proud." },
        { "id": 44, "text": "I finish what matters and let go of what does not." },
        { "id": 45, "text": "I feed my spirit. I train my body. I focus my mind. This is my time." },
        { "id": 46, "text": "My life has meaning. What I do has meaning. My actions are meaningful and inspiring." },
        { "id": 47, "text": "What I have done today was the best I was able to do today. And for that, I am thankful." },
        { "id": 48, "text": "One small positive thought in the morning can change my whole day. So, today I rise with a powerful thought to set the tone and allow success to reverberate through every moment of my day." },
        { "id": 49, "text": "I set goals and go after them with all the determination I can muster. When I do this, my own skills and talents will take me to places that amaze me." },
        { "id": 50, "text": "Happiness is a choice, and today I choose to be happy." }
      
      
];
export default affirmation;